### PR TITLE
Depend on carrierwave 1.0

### PR DESCRIPTION
**Pull request by codegoalie**
Fixes: #6

Let me know if this is too far forward. We could use `>=` to get pre-1.0 too.

### CODE REVIEW

**Comment by codegoalie** [comment]
Looks like decrypting the keyfile is failing on Travis.

**Comment by johnmcconnell** [comment]
Do gemfile's allow a way for the upstream consumer to determine the version dependencies.

It would be easy to test the dependency bump in a staging environment...

**Comment by jasdeepsingh** [comment]
@codegoalie not sure how you got the dependency bump working, I'm getting this error when running the specs locally: 

```
uninitialized constant CarrierWave::Utilities::Uri::URI (NameError)
```

**Comment by jasdeepsingh** [comment]
@codegoalie what Ruby version are you on?

**Comment by codegoalie** [comment]
@jasdeepsingh So sorry! I think my email notifications are messed and I never saw these responses until now.

I'm on Ruby 2.4.1p111.

However, I get that same error if I don't use `bundle exec` to run RSpec.

```
$ bundle exec rspec spec

Randomized with seed 38818

Copying Files
  copies an existing file to the specified path

...
Finished in 27.73 seconds (files took 0.38953 seconds to load)
22 examples, 0 failures

Randomized with seed 38818

$ rspec spec 
/home/codegoalie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/carrierwave-1.1.0/lib/carrierwave/utilities/uri.rb:5:in `<module:Uri>': uninitialized constant CarrierWave::Utilities::Uri::URI (NameError)
Did you mean?  CarrierWave::Utilities::Uri
        from /home/codegoalie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/carrierwave-1.1.0/lib/carrierwave/utilities/uri.rb:3:in `<module:Utilities>'
```

**Comment by jasdeepsingh** [comment]
@codegoalie ok thanks, i'll look at it again.

**Comment by jasdeepsingh** [comment]
> Looks like decrypting the keyfile is failing on Travis.

Turns out this is failing because encrypted secrets are not available to forks.

**Comment by jasdeepsingh** [comment]
Merging this into `development` branch to test it's CI status on Travis.

**Pull request merged**
