### PR TITLE
Fix carrierwave dependency, support 2.0 version

### PR DESCRIPTION
**Pull request by anilmaurya**

### CODE REVIEW

**Comment by jasdeepsingh** [comment]
@anilmaurya Are you having any issues with `1.3.x` version of Carrierwave? Can you explain your reasoning behind this proposal please?

**Comment by anilmaurya** [comment]
@jasdeepsingh I want to use carrierwave latest version i.e `2.0.2`, with current dependency it's not possible therefore this PR.

**Comment by jasdeepsingh** [comment]
This gem is currently not compatible with carrierwave 2.x

Did you tried to run the specs after bumping the carrierwave dependency?

**Comment by anilmaurya** [comment]
No, I didn't ran specs but its working fine with carrierwave 2.x

**Pull request closed without merging**
